export const money = n => `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export const label = s => (s || "").toLowerCase().replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
export const dateLabel = d => d ? new Date(`${d.slice(0, 10)}T12:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
export const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
export const PackageSummary = ({ value: p, prefix = "package-summary", compact = false }) => <section className="border-y border-teal-100 bg-teal-50/40 py-4 px-3" data-testid={prefix}>
  <div className="flex flex-wrap items-center justify-between gap-2 mb-3"><h2 className="font-display text-base font-semibold text-teal-900" data-testid={`${prefix}-name`}>{p.name} <span className="text-xs font-sans font-normal text-gray-500">{p.package_uid}</span></h2>{!compact && <div className="flex flex-wrap gap-2"><PackageStatus value={p.package_status} testId={`${prefix}-status`} /><PackageStatus value={p.payment_status} testId={`${prefix}-payment-status`} /></div>}</div>
  <dl className={`grid grid-cols-2 ${compact ? "lg:grid-cols-3" : "lg:grid-cols-4"} gap-x-5 gap-y-3 text-sm`}>
    {[['treatment', 'Disease / Treatment', p.treatment_name], ['duration', 'Duration', p.duration_label || `${p.duration_value} ${p.duration_value === 1 ? 'month' : 'months'}`], ['start', 'Package start', dateLabel(p.start_date)], ['end', 'Package end / renewal', dateLabel(p.end_date)], ['amount', 'Package amount', money(p.amount ?? p.amount_paise / 100)], ...(!compact ? [['paid', 'Total paid', money(p.total_paid)], ['balance', 'Outstanding', money(p.outstanding)], ['renewal', 'Renewal status', label(p.renewal_status)]] : [])].map(([key, title, val]) => <div key={key} className="min-w-0"><dt className="text-xs text-gray-500 mb-1">{title}</dt><dd className={`break-words ${key === 'balance' && p.outstanding > 0 ? 'text-rose-700' : 'text-gray-900'} font-medium tabular-nums`} data-testid={`${prefix}-${key}`}>{val}</dd></div>)}
  </dl>
</section>;
export const PackageStatus = ({ value, testId }) => <span data-testid={testId} className={`inline-block text-xs px-2 py-1 border rounded-md ${["FULLY_PAID", "ACTIVE", "COMPLETED"].includes(value) ? "border-teal-200 text-teal-800 bg-teal-50" : ["EXPIRED", "UNPAID", "REQUIRES_FOLLOWUP"].includes(value) ? "border-rose-200 text-rose-800 bg-rose-50" : "border-amber-200 text-amber-800 bg-amber-50"}`}>{label(value)}</span>;