import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, fmtErr } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, RotateCcw, CalendarPlus, Check, Loader2 } from "lucide-react";
import { PackageSummary, PackageStatus, money, dateLabel, today, label } from "@/components/packages/PackageSummary";
import { PackagePaymentForm } from "@/components/packages/PackagePaymentForm";
import { PackageForm } from "@/components/packages/PackageForm";
import { PackageLedger } from "@/components/packages/PackageLedger";

export default function PackageDetail() {
  const { id } = useParams(), { user } = useAuth(), navigate = useNavigate();
  const [data, setData] = useState(null), [error, setError] = useState(""), [renewing, setRenewing] = useState(false), [busy, setBusy] = useState(false);
  const [followup, setFollowup] = useState({ scheduled_date: today(), message: "Package follow-up" });
  const [reversal, setReversal] = useState(null), [reason, setReason] = useState("");
  const privileged = ["ADMIN", "OWNER_DOCTOR"].includes(user?.role);
  const readOnly = user?.role === "DOCTOR";
  const load = async () => { const r = await api.get(`/packages/${id}`); setData(r.data); };
  useEffect(() => { setData(null); setError(""); setRenewing(false); load().catch(e => setError(fmtErr(e))); }, [id]);
  const action = async (path, body) => { setBusy(true); setError(""); try { await api.post(path, body); await load(); return true; } catch (e) { setError(fmtErr(e)); return false; } finally { setBusy(false); } };
  if (!data) return <div className="p-6" data-testid="package-detail-loading">{error || <Loader2 className="animate-spin" />}</div>;
  const p = data.package;
  return <div className="p-4 sm:p-6 lg:p-8 max-w-6xl mx-auto space-y-6" data-testid="package-detail-page">
    <Link to="/pro/packages" className="inline-flex items-center gap-1 text-sm text-gray-500" data-testid="back-to-packages"><ArrowLeft size={15} />Packages & dues</Link>
    <header><p className="text-xs text-gray-500" data-testid="package-detail-patient-uid">{data.patient?.patient_uid}</p><h1 className="font-display text-2xl sm:text-3xl font-semibold break-words" data-testid="package-detail-patient-name">{data.patient?.first_name} {data.patient?.last_name}</h1><a href={`tel:${data.patient?.phone}`} className="text-sm text-teal-700" data-testid="package-call-patient">{data.patient?.phone}</a></header>
    <PackageSummary value={p} />
    {error && <p role="alert" className="text-red-700 text-sm" data-testid="package-detail-error">{error}</p>}
    {!readOnly && <div className="grid lg:grid-cols-2 gap-x-10 gap-y-6">
      <section><PackagePaymentForm key={p.id} value={p} onSaved={load} /><div className="border-t border-gray-200 py-5"><h2 className="font-display font-semibold text-base mb-3">Renewal</h2><p className="text-sm text-gray-600 mb-3" data-testid="package-renewal-eligibility">{p.renewal_eligible ? `Eligible from ${dateLabel(p.end_date)}` : p.renewal_status === "REQUIRES_FOLLOWUP" ? `Requires follow-up · Outstanding ${money(p.outstanding)}` : p.package_status === "RENEWED" ? "Renewed · Previous terms and payments retained" : `Renewal date: ${dateLabel(p.end_date)}`}</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!p.renewal_eligible || busy} onClick={() => setRenewing(true)} data-testid="renew-package-button"><RotateCcw size={15} />Renew package</Button>{privileged && p.lifecycle === "OPEN" && p.outstanding === 0 && <Button variant="outline" disabled={busy} onClick={() => { const why = window.prompt("Reason for completing this package (at least 5 characters)"); if (why) action(`/packages/${id}/complete`, { reason: why }); }} data-testid="complete-package-button"><Check size={15} />Mark completed</Button>}</div></div></section>
      <section className="py-5"><h2 className="font-display text-base font-semibold mb-4">PRO follow-up</h2><form onSubmit={async e => { e.preventDefault(); await action(`/packages/${id}/followups`, followup); }} className="space-y-3" data-testid="package-followup-form"><label className="text-sm block">Next follow-up<Input required type="date" min={today()} value={followup.scheduled_date} onChange={e => setFollowup(f => ({ ...f, scheduled_date: e.target.value }))} className="mt-2" data-testid="package-followup-date" /></label><label className="text-sm block">Follow-up note<Textarea required maxLength={1000} value={followup.message} onChange={e => setFollowup(f => ({ ...f, message: e.target.value }))} className="mt-2" data-testid="package-followup-note" /></label><Button disabled={busy} variant="outline" data-testid="save-package-followup"><CalendarPlus size={15} />Schedule follow-up</Button></form><div className="divide-y mt-4">{data.followups.map(r => <div key={r.id} className="py-3 flex gap-3 justify-between items-start" data-testid={`package-followup-${r.id}`}><div className="text-sm min-w-0"><strong>{dateLabel(r.scheduled_date)}</strong><p className="break-words text-gray-600">{r.message}</p><span className="text-xs text-gray-500">{label(r.status)}</span></div>{r.status === "PENDING" && <Button variant="ghost" disabled={busy} onClick={() => action(`/packages/${id}/followups/${r.id}/complete`)} data-testid={`complete-package-followup-${r.id}`}><Check size={15} />Complete</Button>}</div>)}</div></section>
    </div>}
    {renewing && !readOnly && <PackageForm patientId={p.patient_id} previous={p} onCancel={() => setRenewing(false)} onSaved={next => { setRenewing(false); navigate(`/pro/packages/${next.id}`); }} />}
    {reversal && <form className="bg-rose-50 border border-rose-200 p-4 rounded-md space-y-3" data-testid="reversal-form" onSubmit={async e => { e.preventDefault(); if (await action(`/packages/${id}/payments/${reversal.id}/reverse`, { reason, idempotency_key: reversal.requestKey })) setReversal(null); }}><h2 className="text-base font-semibold">Reverse {reversal.receipt_no} · {money(reversal.amount)}</h2><Textarea required minLength={5} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason for reversal" data-testid="reversal-reason" /><div className="flex gap-2"><Button disabled={busy} variant="destructive" data-testid="confirm-reversal">Confirm reversal</Button><Button type="button" variant="outline" onClick={() => setReversal(null)} data-testid="cancel-reversal">Cancel</Button></div></form>}
    <PackageLedger value={p} canReverse={privileged} readOnly={readOnly} onReverse={t => { setReason(""); setReversal({ ...t, requestKey: crypto.randomUUID() }); }} />
    <section className="border-t border-gray-200 py-5"><h2 className="font-display text-base font-semibold mb-3">Visits / bills</h2>{data.bills.length === 0 && <p className="text-sm text-gray-500" data-testid="package-bills-empty">No visits linked yet.</p>}<div className="divide-y">{data.bills.map(b => { const paid = p.transactions.filter(t => t.case_id === b.case_id).reduce((sum, t) => sum + t.amount, 0); return <div key={b.case_id} className="flex flex-wrap gap-3 justify-between py-3 text-sm" data-testid={`package-bill-${b.case_id}`}><span>{b.receipt_no} · {dateLabel(b.created_at)}</span><span data-testid={`package-visit-paid-${b.case_id}`}>{money(paid)} {paid === 0 ? "· No payment" : ""}</span>{!readOnly && <Link to={`/pro/cases/${b.case_id}`} className="text-teal-700" data-testid={`package-visit-link-${b.case_id}`}>Open visit</Link>}</div>; })}</div></section>
    <section className="border-t border-gray-200 py-5"><h2 className="font-display text-base font-semibold mb-4">Treatment package history</h2><div className="space-y-3">{data.history.map(h => <div key={h.id} className="border-l-2 border-teal-200 pl-4 py-2 flex flex-wrap gap-3 justify-between" data-testid={`package-history-${h.id}`}><div className="text-sm"><Link to={`/pro/packages/${h.id}`} className="font-medium text-teal-800" data-testid={`package-history-link-${h.id}`}>{h.package_uid} · {h.name}</Link><div className="text-gray-500 mt-1">{dateLabel(h.start_date)} → {dateLabel(h.end_date)} · {h.duration_label}</div><div className="mt-1" data-testid={`package-history-balance-${h.id}`}>{money(h.amount)} · Paid {money(h.total_paid)} · Outstanding {money(h.outstanding)}</div>{h.previous_package_id && <div className="text-xs text-gray-500">Renewed from {data.history.find(x => x.id === h.previous_package_id)?.package_uid}</div>}</div><PackageStatus value={h.package_status} testId={`package-history-status-${h.id}`} /></div>)}</div></section>
  </div>;
}